spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: rootroot
    url: jdbc:mysql://127.0.0.1:3306/12345678?useUnicode=true&characterEncoding=utf-8&allowMultiQueries=true
#全局命名策略
  jpa:
    hibernate:
      ddl-auto: update
      naming:
        implicit-strategy: com.pay.mgr.web.support.TableNamingStrategy
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    generate-ddl: true


